apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: gateway-deployment
spec:
    replicas: 1
    template:
        metadata:
          labels:
            app: gateway-app
        spec:
          containers:
          - name: gateway-service
            image: gcr.io/sfelix-224423/gateway-service
            ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-app
  ports:
    - port: 8080
      targetPort: 8080