apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dog-deployment
spec:
    replicas: 1
    template:
        metadata:
          labels:
            app: dog-app
        spec:
          containers:
          - name: dog-service
            image: gcr.io/sfelix-224423/dog-service
            ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dog-service
spec:
  type: NodePort
  selector:
    app: dog-app
  ports:
    - port: 8080
      targetPort: 8080